# Generated by Django 3.0.5 on 2020-05-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='author',
        ),
    ]
