# Generated by Django 3.0.5 on 2020-06-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_message_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
