# Generated by Django 3.0.5 on 2020-06-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200611_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='username',
        ),
    ]
